### ISSUE TITLE
O1.3.1 Update terminal velocity formulae

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#154]
Done:
- [x] rain drops (combine with Seifert Beheng 2006 scheme)
- [x] snow/ice/rain (combine with 1-moment scheme)
- [x] documentation
- [x] test
- [x] usage example from KiD

We need to update the bulk 1 -moment microphysics scheme to use the Chen 2022 velocities in all the internals.

```[tasklist]
###  Equations
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/220
- [ ] https://github.com/CliMA/CloudMicrophysics.jl/issues/221
```
```[tasklist]
###  Computing rates
- [ ] accretion
- [ ] rain evaporation (via ventilation factor)
- [ ] deposition/sublimation (via ventilation factor)
- [ ] melting (via ventilation factor)
```
```[tasklist]
### Spherical assumptions
- [ ] mass transfer equations
- [ ] collision kernel
- [ ] Reynolds number in ventilation factors
```

**Comment by apoorva-thanvantri** [comment]
![IMG_0015](https://github.com/CliMA/CloudMicrophysics.jl/assets/67611070/5f741f5c-ea20-4591-a3ac-c6e29f6b5471)
![IMG_0016](https://github.com/CliMA/CloudMicrophysics.jl/assets/67611070/3f2bb63e-0184-4518-9f78-38229a0f7039)
![IMG_0017](https://github.com/CliMA/CloudMicrophysics.jl/assets/67611070/2d7ff3ca-3955-493a-991f-b0ba54169170)
![IMG_0018](https://github.com/CliMA/CloudMicrophysics.jl/assets/67611070/08f652c9-cb13-4e9f-9f75-bc11e1266187)
![IMG_0019](https://github.com/CliMA/CloudMicrophysics.jl/assets/67611070/918e1ee7-7baa-4a3f-b077-778d6291240a)

Some computations I did! I didn't double check them so they might be wrong (but I thought they might be useful anyways)

**Comment by trontrytel** [comment]
Thank you!

**Comment by trontrytel** [comment]
In the spirit of keeping the 1-moment scheme simple, we will not be updating it's velocities to Chen 2022. 

We will keep using Chen 2022 in the P3 scheme and have it as option in the 2-moment scheme
