### ISSUE TITLE
Make P3 scheme GPU compatible

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#177]

**Comment by trontrytel** [comment]
We will probably want to do #176 first. This is not a high priority, though. We will want to first run the 0-moment and 1-moment schemes on the GPUs. And they don't require any non-linear solvers to work

**Comment by trontrytel** [comment]
@charleskawczynski, @sriharshakandala - could you take a look [here](https://github.com/CliMA/CloudMicrophysics.jl/blob/41b30502c11ae8a8b42c6fc69348314463258557/src/P3Scheme.jl#L136-L152). This is where we define our non-linear solver for the P3 scheme. We currently use the `NonlinearSolve` package.

Would it be enough to replace the Vector with an Array/CuArray?  `NonlinearSolve` does not accept a tuple.
AFAIK they have [one GPU test](https://github.com/SciML/NonlinearSolve.jl/blob/master/test/gpu.jl)

I know we have our `RootSolvers.jl` but I don't know how to apply them to my set of 4 coupled equations.

**Comment by charleskawczynski** [comment]
Yeah, we need a different kind of GPU compatibility-- this entire function will be executed inside a gpu kernel. It's a bit different from what they're doing. There is https://github.com/CliMA/NonlinearSolvers.jl, but the RootSolvers route may be better if you can reformulate things.

To reformulate for RootSolvers, we'll need to combine the equations until there is 1 equation and 1 unknown (we'll need to choose which one to solve for). Then, once we've found the root that satisfies this equation, we can use that to compute the other unknowns. So, for example, if we wanted to solve for `ρ_g`, we could combine the equations to compute the root:

```julia
root(_ρ_g) = _ρ_g - ρ_g_helper(p.ρ_r, p.F_r, ρ_d_helper(p.p3, D_cr_helper(p.p3, p.F_r, _ρ_g), D_gr_helper(p.p3, _ρ_g)))
```

One nice advantage of this is that-- we don't need StaticArrays / Tuples at all, there is a single scale of the root equation (`(_ρ_g`) as opposed to multiple scales. For example, how do you compute the norm of the residual for determining convergence for the nonlinear equation in the multiple equations case? If you want a relative tolerance, you'll need multiple scales to compute the relative tolerances per equation. On the one hand, it's more fine grained, on the other, it complicates the interface, and introduces an ordering to the inputs (the inputs/outputs need to be in a Tuple or Vector), which is not ideal. We could theoretically map the ordering to variables, but that would further complicate things.

**Comment by trontrytel** [comment]
Thanks! I see it now. I'll test if what you suggested works 🤞  That would be the easiest thing to do dependency wise
