### ISSUE TITLE
Qualify inputs

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#20]
As suggested here https://github.com/CliMA/CloudMicrophysics.jl/pull/18#discussion_r689787075

Do this:

```
import Thermodynamics
TD = Thermodynamics
TD.air_temperature(ts)
```
throughout the package.

**Comment by jakebolewski** [comment]
In Julia 1.6 (I'm unsure of 1.5) you can achieve this with `import Thermodynamics as TD`  similar to python.

**Comment by trontrytel** [comment]
resolved
