### ISSUE TITLE
Find parameterization for water activity at T > 235K

### ISSUE THREAD

**Issue by amylu00** [CliMA/CloudMicrophysics.jl#200]
Current parameterization for H2SO4 saturated vapor pressure is only valid for temperatures up to 235K. Because of that, any freezing mode dependent on the water activity of the solution droplet (ABIFM and Homogeneous) would not be valid for warmer temperatures (mixed phase clouds)

**Comment by trontrytel** [comment]
Some papers to take a look at:
- [Ganbavale et al 2014](https://doi.org/10.5194/acp-14-9993-2014)
- [Zobrist et al 2008](https://doi.org/10.5194/acp-8-5221-2008)

**Comment by trontrytel** [comment]
Closing. Seems like we are using RH for now
