### ISSUE TITLE
Delete x_sulph from parcel

### ISSUE THREAD

**Issue by amylu00** [CliMA/CloudMicrophysics.jl#232]
Parcel model currently takes in a constant sulphuric acid concentration. The concentration should decrease with increasing droplet/crystal size.

**Comment by trontrytel** [comment]
I think the easiest would be to track the mean x_sulph = initial_moles (or mass etc) / mean volume (proportional to the third moment of the size distribution) ?

**Comment by trontrytel** [comment]
Lets delete it from parcel.
