### ISSUE TITLE
Compat helper PRs

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#25]
What is up with all the compat helper PRs https://github.com/CliMA/CloudMicrophysics.jl/pulls

They all seem to be hanging? Is there anything on the packages side that we could do to fix this? @charleskawczynski @jakebolewski

**Comment by jakebolewski** [comment]
you need to close them or `bors r+` them in, or we can get rid of them as I too think they are noisy and you can just manually update your dependencies.

**Comment by trontrytel** [comment]
I thought they were supposed to go in automatically. I'll bors r+ them and close the ones that will fail. Thanks!
