### ISSUE TITLE
Compare with ARG 2000

### ISSUE THREAD

**Issue by trontrytel** [CliMA/CloudMicrophysics.jl#30]
Add more comparison plots with the original paper.

**Comment by claresinger** [comment]
See new branch: https://github.com/CliMA/CloudMicrophysics.jl/tree/ces/ARGplots

Figs 1-5 compared against ARG2000 and PySDM here:
[fig_1.pdf](https://github.com/CliMA/CloudMicrophysics.jl/files/8548710/fig_1.pdf)
[fig_2.pdf](https://github.com/CliMA/CloudMicrophysics.jl/files/8548711/fig_2.pdf)
[fig_3.pdf](https://github.com/CliMA/CloudMicrophysics.jl/files/8548712/fig_3.pdf)
[fig_4.pdf](https://github.com/CliMA/CloudMicrophysics.jl/files/8548713/fig_4.pdf)
[fig_5.pdf](https://github.com/CliMA/CloudMicrophysics.jl/files/8548714/fig_5.pdf)

Discovered one bug/feature while doing this. The code right now expects that the aerosol modes all have the same number of components. I hacked my way around this for now, but we should fix this for the future. https://github.com/CliMA/CloudMicrophysics.jl/blob/0a1b181578660ff76226c4919064f7ffbc0c5a51/docs/src/ARGplots.jl#L50-L82
