### ISSUE TITLE
Define convenience structs with only the toml dict

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/CloudMicrophysics.jl#345]
It would be nice if every package defined a method for constructing parameters with only the toml dict, for example:

```julia
cm_params = CloudMicrophysics.Parameters.Parameters0M(toml_dict)
```

We don't actually need `FT`, since the toml dict already has that.

**Comment by charleskawczynski** [comment]
An `FT` method is nice, too, but a `toml_dict` one is more flexible

**Comment by trontrytel** [comment]
We have something like this for all the parameter structs: https://github.com/CliMA/CloudMicrophysics.jl/blob/7b0de4f39dd6685e466c6f22f72ddc86b5cd3623/src/parameters/Microphysics0M.jl#L23

Do we need something more?
